.gitignore
src/main/java/org/apache/commons/cli/DefaultParser.java
src/test/java/org/apache/commons/cli/DisablePartialMatchingTest.java

At request of Gary, I (re)created an old patch against the current code base to enable partial matching to be set as optional. This fixes problems for people that have short options that, concatenated, also partial-match a long option.
For example:
-d, --debug
-e, --extract
foo -de
Is ambiguous in the case that partial matching is enabled. This patch allows a user to turn off partial matching in such a case.

CLI-217: Optional partial matching

---

.travis.yml

(see https://github.com/travis-ci/travis-ci/issues/8199)

.travis.yml: install open-jdk6, as it was removed from the default image

---

src/site/xdoc/usage.xml

[`OptionBuilder`](https://commons.apache.org/proper/commons-cli/apidocs/org/apache/commons/cli/OptionBuilder.html) is deprecated. Since 1.3, use [`Option.builder(String)`](https://commons.apache.org/proper/commons-cli/apidocs/org/apache/commons/cli/Option.html#builder(java.lang.String)) instead.

Docs: Replace OptionBuilder in usage page

---

.travis.yml

Fix broken build [589473088](https://travis-ci.org/apache/commons-cli/builds/589473088) (triggered by https://github.com/apache/commons-cli/commit/684b3c9eb54aa7d5328d1a4e2583c3dbdfe64465) by switching from Oracle JDK 8 to Open JDK 8. Open JDK 8 has already been used by other repositories of Apache Commons, such as [commons-math](https://github.com/apache/commons-math/blob/master/.travis.yml#L20), [commons-io](https://github.com/apache/commons-io/blob/master/.travis.yml#L20), and [commons-lang](https://github.com/apache/commons-lang/blob/master/.travis.yml#L18).

Switch from Oracle JDK 8 to Open JDK 8

---

.gitignore

This is similar to how [commons-logging](https://github.com/apache/commons-logging/blob/master/.gitignore#L16-L20) does it.

Git ignore all IntelliJ files

---

src/site/xdoc/index.xml

Both of these [links](https://commons.apache.org/proper/commons-cli/index.html) cause 404 errors.

Fix site links that are broken

---

pom.xml
src/main/java/org/apache/commons/cli/OptionValidator.java
src/test/java/org/apache/commons/cli/OptionValidatorTest.java

Fix for CLI-322
Adds kabab-format options and extensive option name testing.

CLI-322: Add '-' as an option char and implemented extensive tests

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/test/java/org/apache/commons/cli/CommandLineTest.java

Fix for CLI-323 https://issues.apache.org/jira/browse/CLI-323

[CLI-323] Added Supplier<T> defaults for getParsedOptionValue

---

src/main/java/org/apache/commons/cli/Option.java
src/test/java/org/apache/commons/cli/AbstractParserTestCase.java

What it boils down to can be seen by looking at the `opts.addOption` lines in the supplied testCase (lines 736 and 760).
For 1.5.0, any of the following worked for creating the Option:
```
OptionBuilder.hasOptionalArgs(2).create('i')
Option.builder("i").optionalArg(true).numberOfArgs(2).build()
Option.builder("i").numberOfArgs(2).optionalArg(true).build()
```
For 1.6.0, the last variant now fails. The PR reinstates that variant.

CLI-320: Awkward behavior of Option.builder() for multiple optional args

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/test/java/org/apache/commons/cli/bug/BugCLI325Test.java

When properties are retrieve for an Option that has both multiple arguments and a value separator only the first is retrieved.  This fixes that issue
fix for CLI-325

CLI-325: properties from multiple arguments with value separator.

---

src/main/java/org/apache/commons/cli/Option.java

CLI-326: make option.getKey() public

---

src/test/java/org/apache/commons/cli/ConverterTests.java
src/test/java/org/apache/commons/cli/PatternOptionBuilderTest.java
src/test/java/org/apache/commons/cli/TypeHandlerTest.java

Fixes for CLI-327
In some cases the time zone for the expected date string is different than the hard coded version.  This change creates the expected value from a known simple date format of the Date argument so that the expected value always matches the produced time zone.

[CLI-327] Fix for expected textual date values.

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/main/java/org/apache/commons/cli/DefaultParser.java
src/main/java/org/apache/commons/cli/DeprecatedAttributes.java
src/main/java/org/apache/commons/cli/HelpFormatter.java
src/main/java/org/apache/commons/cli/Option.java
src/test/java/org/apache/commons/cli/CommandLineTest.java
src/test/java/org/apache/commons/cli/DefaultParserTest.java
src/test/java/org/apache/commons/cli/DeprecatedAttributesTest.java
src/test/java/org/apache/commons/cli/OptionTest.java
src/test/java/org/apache/commons/cli/OptionsTest.java
src/test/java/org/apache/commons/cli/SolrCliTest.java
src/test/java/org/apache/commons/cli/SolrCreateToolTest.java

https://issues.apache.org/jira/browse/CLI-329
Adds support to allow deprecation of Option objects.
A simple example:
```
final Option opt1 = Option.builder().option("d1").deprecated().build();
```
A more detailed example:
```
final Option opt2 = Option.builder().option("d2").deprecated(DeprecatedAttributes.builder()
.setForRemoval(true)      // Like the Deprecated annotation
.setSince("1.0")          // Like the Deprecated annotation
.setDescription("Do this instead.").get()).build(); // Like the Deprecated Javadoc tag
```

[CLI-329] Support "Deprecated" CLI Options

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/test/java/org/apache/commons/cli/CommandLineTest.java

Fixes [CLI-331](https://issues.apache.org/jira/browse/CLI-331)

[CLI-331] Handle reporting of deprecated options when parameters are not String type.

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/main/java/org/apache/commons/cli/HelpFormatter.java
src/site/xdoc/usage.xml
src/test/java/org/apache/commons/cli/CommandLineTest.java
src/test/java/org/apache/commons/cli/HelpFormatterTest.java

Changes based on my review of the main branch prior to release while writing additional documentation.

Cleanup deprecation issues

---

src/main/java/org/apache/commons/cli/HelpFormatter.java
src/site/xdoc/usage.xml
src/test/java/org/apache/commons/cli/HelpFormatterTest.java

Changes to simplify deprecated help output.
- Changed `deprecatedFormatFunc` from  `BiFunction<String, Option, String>` to `Function<Option,String>`
- updated docs
- added `HelpFormatter.getDescription(Option)` to provide a function does not return null for `getDescription`

Cleanup help formatting

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/main/java/org/apache/commons/cli/OptionGroup.java
src/test/java/org/apache/commons/cli/CommandLineTest.java

fixes for CLI-336 
updated javadoc for OptionGroup.getSelected(), OptionGroup.isSelected() and OptionGroup.select() methods to indicate that deprecated options do not trigger logging of deprecated option usage.
CommandLine methods hasOption(OptionGroup), getOptionValue(OptionGroup), getOptionValues(OptionGroup),  and getParsedOptionValue(OptionGroup) methods.

[CLI-336] Deprecation not always reported

---

src/main/java/org/apache/commons/cli/HelpFormatter.java
src/main/java/org/apache/commons/cli/Option.java
src/test/java/org/apache/commons/cli/HelpFormatterTest.java

Adds a `since` attribute to options but does not modify the display by default.
Adds `showSince` to HelpFormatter and HelpFormatter.Builder
When `since` is shown a header line above the Option listing is added delineating the  "Options", "Since", and "Description" sections.
Appropriate tests were added.

Add "since" attribute to Option to track when an Option was introduced.

---

src/test/java/org/apache/commons/cli/DefaultParserTest.java

- Satisfy the TODO comment
- Fill out the missing cases
- Long option quote handling DEFAULT behavior
- Short option quote handling DEFAULT behavior
- Short option concatenated quote handling WITH strip
- Short option concatenated quote handling WITHOUT strip

Refactor default parser test

---

pom.xml

Get mockito version from parent pom

---

src/main/java/org/apache/commons/cli/DefaultParser.java
src/test/java/org/apache/commons/cli/DefaultParserTest.java

Goal is to introduce new "ops" for CLI parser: a mode when unknown options are completely ignored or just skipped (added to args). At the same time encapsulation is loosened as well, by making relevant methods `protected` to allow possible override/extension of `DefaultParser` class.
---
Simpler variation of #378
Goal: to "postpone" full argument parsing. To be used in Maven. We introduced new "cli commands" aside of existing `mvn`, like `mvnenc`, `mvnsh` and `mvnup`. 
The "base" options (all CLI command) are these:
https://github.com/apache/maven/blob/77ebd14d1580e0a67c5a929afdd3ac62a3bfea1f/api/maven-api-cli/src/main/java/org/apache/maven/api/cli/Options.java
And each command _extends_ this base with specific options, for example: …

Add new options for parsing: ignore and skip

---

src/main/java/org/apache/commons/cli/CommandLine.java
src/test/java/org/apache/commons/cli/OptionCountTest.java

Implements [CLI-350](
https://issues.apache.org/jira/browse/CLI-350)

Add getOptionCount to CommandLine to measure option repetition
